#!/bin/bash --login
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=2
#PBS -N 2018_attempt1
#PBS -A d411-training
cd $PBS_O_WORKDIR
#module load Miniconda2
module load miniconda/python2
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
#validate mapping file
validate_mapping_file.py -m map_complete.tsv -o vmf
source deactivate
