#!/bin/bash --login
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=2
#PBS -N 2018_attempt1
#PBS -A d411-training
cd $PBS_O_WORKDIR
# setting temporary directory
export TMPDIR=~/qiime_tmp
#module load Miniconda2
module load miniconda/python2
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
#join paired ends
join_paired_ends.py -f Read1.fastq -r Read2.fastq -b Index.fastq -o fastq-join_joined
source deactivate
