#!/bin/bash --login
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=2
#PBS -N 2018_attempt1
#PBS -A d411-training
cd $PBS_O_WORKDIR
# setting temporary directory
export TMPDIR=~/qiime_tmp

module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"
source activate qiime1

# splitting libraries
echo "splitting libraries"
split_libraries_fastq.py --barcode_type 12 -i fastq-join_joined/fastqjoin.join.fastq -b fastq-join_joined/fastqjoin.join_barcodes.fastq -o slout -m map_complete.tsv -q 19 --rev_comp_barcode --rev_comp_mapping_barcodes

source deactivate
