#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=22
#PBS -N 2018_attempt_otu
#PBS -A d411-training
cd $PBS_O_WORKDIR
#setting temporary directory
export TMPDIR=~/qiime_tmp

module load miniconda/python2
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
#pick OTUs closed reference
echo "Picking OTUs with closed reference"
pick_closed_reference_otus.py -i slout/seqs.fna -o otus -a -O 16
source deactivate
