#!/bin/bash --login
#PBS -l walltime=10:00:00
#PBS -l select=1:ncpus=24
#PBS -N 2018_open_otu_gg
#PBS -A d411-training
cd $PBS_O_WORKDIR
#setting temporary directory
export TMPDIR=~/qiime_tmp

module load miniconda/python2
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
#pick OTUs open reference with greengenes
echo "Picking OTUs with open reference"
pick_open_reference_otus.py -i slout/seqs.fna -o otus_open -a -O 24

source deactivate
