#!/bin/bash --login
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=2
#PBS -N 2018_gg_summarize_tax
#PBS -A d411-training
cd $PBS_O_WORKDIR
# setting temporary directory
export TMPDIR=~/qiime_tmp

module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"
source activate qiime1

# summarize taxa to lvl 2 in absolute proportions CLOSED REFERENCE
summarize_taxa.py -i ~/2018_v2/filtered/filtered_otu_table_closed.biom -L 2 -o ~/2018_v2/filtered/taxa_closed_relative

#same but OPEN REFERENCE
summarize_taxa.py -i ~/2018_v2/filtered/filtered_otu_table_open.biom -L 2 -o ~/2018_v2/filtered/taxa_open_relative

source deactivate
