#!/bin/bash --login
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=2
#PBS -N 2018_filtering
#PBS -A d411-training
cd $PBS_O_WORKDIR
# setting temporary directory
export TMPDIR=~/qiime_tmp

module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"
source activate qiime1

# filtering the non Gordon Square samples closed reference
filter_samples_from_otu_table.py -i otus_closed/otu_table.biom -o filtered/filtered_otu_table_closed.biom --sample_id_fp ids.txt --negate_sample_id_fp

#filtering non GS open reference
filter_samples_from_otu_table.py -i otus_open/otu_table_mc2_w_tax_no_pynast_failures.biom -o filtered.filtered_otu_table_open.biom --sample_id_fp ids.txt --negate_sample_id_fp


source deactivate
