#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=22
#PBS -N 2018_attempt_otu
#PBS -A d411-training
cd $PBS_O_WORKDIR
#setting temporary directory
export TMPDIR=~/qiime_tmp
#loading pyhton
module load miniconda/python2
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
#core diversity analysis
echo "Performing core diversity analysis"
core_diversity_analyses.py --recover_from_failure -o filtered/cdout -i filtered/filtered_otu_table_open.biom -m filtered/map_filtered.tsv -t otus_open/rep_set.tre -e 39504

source deactivate
