#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=24
#PBS -N 2018_alpha_rarefaction
#PBS -A d411-training
cd $PBS_O_WORKDIR
# setting temporary directory
export TMPDIR=~/qiime_tmp

module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"
source activate qiime1

# alpha rarefaction with no sampling depth
alpha_rarefaction.py -i filtered/filtered_otu_table_closed.biom -o filetered/full_rarefaction -t otus_closed/97_otus.tree -m map_complete.tsv -a -O 24

source deactivate
